import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import ConvexClientProvider from '../components/providers/ConvexClientProvider'
import { AuthButtons } from "../components/authButtons"
import Navigation from '../components/Navbar'
import { Toaster } from '@/components/ui/sonner'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider>
          <div className="absolute inset-0 -z-10 h-full w-full items-center px-5
          py-24 [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)]">            
          </div>
          <ConvexClientProvider>
            <AuthButtons />
            <Navigation />
            {children}
            <Toaster position="top-center" />
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}
